descrcl.wad
gfx/detail/descrcl/sanddetail1.tga
maps/desertcircle.cfg
maps/desertcircle.res
maps/desertcircle_detail.txt
maps/desertcircle_motd.txt
maps/desertcircle_skl.cfg
models/descrcl/groundLL.mdl
models/descrcl/groundLR.mdl
models/descrcl/groundUL.mdl
models/descrcl/groundUR.mdl
models/descrcl/hgrunt.mdl
models/descrcl/hgrunt01.mdl
models/descrcl/hgrunt02.mdl
models/descrcl/hgrunt03.mdl
models/descrcl/hgruntt.mdl
sound/descrcl/desertwind.wav
sound/descrcl/fanfare.wav
sound/descrcl/flag.wav
sound/descrcl/music1.wav
sound/descrcl/descrclsrf.txt
sound/descrcl/bugs.ogg
sound/descrcl/muezzin.ogg
sprites/descrcl/palmtree1.spr
sprites/descrcl/palmtree1mirror.spr
sprites/descrcl/palmtree2.spr
sprites/descrcl/palmtree2mirror.spr
sprites/descrcl/scteamflag.spr
sprites/descrcl/scteamflagmirror.spr