// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/cliffduskbk.tga
gfx/env/cliffduskdn.tga
gfx/env/cliffduskft.tga
gfx/env/cliffdusklf.tga
gfx/env/cliffduskrt.tga
gfx/env/cliffduskup.tga
models/echoes/5ton.mdl
models/echoes/alyx_hd.mdl
models/echoes/barnacle.mdl
models/echoes/barney.mdl
models/echoes/barney_bshift.mdl
models/echoes/barney_civ.mdl
models/echoes/barney_decay.mdl
models/echoes/barney_hev.mdl
models/echoes/barney_mag.mdl
models/echoes/barney_runner.mdl
models/echoes/barney_wrangler.mdl
models/echoes/boid.mdl
models/echoes/bradley.mdl
models/echoes/bullsquid.mdl
models/echoes/bullsquid01.mdl
models/echoes/clip_scientist.mdl
models/echoes/clip_scientist01.mdl
models/echoes/combat_suv.mdl
models/echoes/combat_suv_anim.mdl
models/echoes/construction.mdl
models/echoes/deadhaz.mdl
models/echoes/Ending_Advisor.mdl
models/echoes/Ending_Dropship.mdl
models/echoes/Ending_Gunship.mdl
models/echoes/Ending_Synth.mdl
models/echoes/EYE_SCANNER.mdl
models/echoes/eye_scanner_broken.mdl
models/echoes/flyer.mdl
models/echoes/flyer_gibs.mdl
models/echoes/food_tray.mdl
models/echoes/fork.mdl
models/echoes/fork_open.mdl
models/echoes/fungus(large).mdl
models/echoes/fungus(small).mdl
models/echoes/fungus.mdl
models/echoes/garg.mdl
models/echoes/gman.mdl
models/echoes/gordon_scientist.mdl
models/echoes/gordon_suit.mdl
models/echoes/gorepile.mdl
models/echoes/hair.mdl
models/echoes/hairt.mdl
models/echoes/hassassin.mdl
models/echoes/headcrab_dead.mdl
models/echoes/hgrunt.mdl
models/echoes/hgrunt01.mdl
models/echoes/hgrunt02.mdl
models/echoes/hgrunt03.mdl
models/echoes/hgrunt04.mdl
models/echoes/hgrunt_medic.mdl
models/echoes/hgrunt_opfor.mdl
models/echoes/hgrunt_torch.mdl
models/echoes/holo1.mdl
models/echoes/holo2.mdl
models/echoes/icky.mdl
models/echoes/islave.mdl
models/echoes/lab_disection_tools1.mdl
models/echoes/lab_disection_tools2.mdl
models/echoes/lab_dissected_headcrab.mdl
models/echoes/lab_experiment.mdl
models/echoes/lab_glasstube.mdl
models/echoes/lab_headless_zombie.mdl
models/echoes/light.mdl
models/echoes/massn.mdl
models/echoes/massn01.mdl
models/echoes/massn02.mdl
models/echoes/mossman_hd.mdl
models/echoes/obj_chair.mdl
models/echoes/osprey.mdl
models/echoes/osprey_bodygibs.mdl
models/echoes/osprey_enginegibs.mdl
models/echoes/osprey_still.mdl
models/echoes/osprey_tailgibs.mdl
models/echoes/otis.mdl
models/echoes/p_squeak.mdl
models/echoes/pcvvest.mdl
models/echoes/qmeal.mdl
models/echoes/sci_crowbar.mdl
models/echoes/sci_gun.mdl
models/echoes/sci_legs.mdl
models/echoes/scientist.mdl
models/echoes/scientist_bshift.mdl
models/echoes/scientist_civ.mdl
models/echoes/scientist_civ_coat.mdl
models/echoes/scientist_civ_paper.mdl
models/echoes/scientist_cleansuit.mdl
models/echoes/scientist_console_civ.mdl
models/echoes/scientist_decay.mdl
models/echoes/scientist_op4.mdl
models/echoes/sentry.mdl
models/echoes/sentryt.mdl
models/echoes/sink.mdl
models/echoes/tree.mdl
models/echoes/truck_research.mdl
models/echoes/v_357.mdl
models/echoes/v_9mmar.mdl
models/echoes/v_9mmhandgun.mdl
models/echoes/v_crossbow.mdl
models/echoes/v_crowbar.mdl
models/echoes/v_egon.mdl
models/echoes/v_grenade.mdl
models/echoes/v_m16a2.mdl
models/echoes/v_medkit.mdl
models/echoes/v_rpg.mdl
models/echoes/v_satchel.mdl
models/echoes/v_shotgun.mdl
models/echoes/v_squeak.mdl
models/echoes/v_tripmine.mdl
models/echoes/w_battery.mdl
models/echoes/w_sqknest.mdl
models/echoes/w_squeak.mdl
models/echoes/worker.mdl
models/echoes/zombie.mdl
models/echoes/zombie_barney.mdl
models/echoes/zombie_barney2.mdl
models/echoes/zombie_burnt.mdl
models/echoes/zombie_construction.mdl
models/echoes/zombie_scientist.mdl
models/echoes/zombie_soldier.mdl
models/echoes/zombie_soldier2.mdl
models/echoes/zombie_soldier3.mdl
sound/echoes/agamemnon/ag_comeon0.wav
sound/echoes/agamemnon/ag_comeon1.wav
sound/echoes/agamemnon/ag_comeon10.wav
sound/echoes/agamemnon/ag_comeon2.wav
sound/echoes/agamemnon/ag_comeon3.wav
sound/echoes/agamemnon/ag_comeon4.wav
sound/echoes/agamemnon/ag_comeon5.wav
sound/echoes/agamemnon/ag_comeon6.wav
sound/echoes/agamemnon/ag_comeon7.wav
sound/echoes/agamemnon/ag_comeon8.wav
sound/echoes/agamemnon/ag_comeon9.wav
sound/echoes/agamemnon/ag_damn.wav
sound/echoes/agamemnon/ag_headroll.wav
sound/echoes/agamemnon/ag_meet0.wav
sound/echoes/agamemnon/ag_meet1.wav
sound/echoes/agamemnon/ag_meet2.wav
sound/echoes/agamemnon/ag_meet3.wav
sound/echoes/agamemnon/ag_meet4.wav
sound/echoes/agamemnon/ag_meet5.wav
sound/echoes/agamemnon/ag_meet6.wav
sound/echoes/agamemnon/ag_meet7.wav
sound/echoes/agamemnon/ag_mic.wav
sound/echoes/agamemnon/ag_music.wav
sound/echoes/agamemnon/ag_paymess.wav
sound/echoes/agamemnon/ag_tv1_0testing.wav
sound/echoes/agamemnon/ag_tv1_1yesgood.wav
sound/echoes/agamemnon/ag_tv1_2anywhere.wav
sound/echoes/agamemnon/ag_tv1_3lift.wav
sound/echoes/agamemnon/ag_tv1_military.wav
sound/echoes/agamemnon/ag_tv1_otherside.wav
sound/echoes/agamemnon/ag_tv2_0gladalive.wav
sound/echoes/agamemnon/ag_tv3_0destroy.wav
sound/echoes/agamemnon/ag_tv4_0foundguard.wav
sound/echoes/agamemnon/ag_tv4_1codes.wav
sound/echoes/agamemnon/ag_tv4_2await.wav
sound/echoes/agamemnon/ag_tv5wrong.wav
sound/echoes/barney/_comma.wav
sound/echoes/barney/ba_attack2.wav
sound/echoes/barney/ba_blocked.wav
sound/echoes/barney/ba_bridgechat1.wav
sound/echoes/barney/ba_crazy.wav
sound/echoes/barney/ba_doorstuck.wav
sound/echoes/barney/ba_generic2.wav
sound/echoes/barney/ba_getthroughthis.wav
sound/echoes/barney/ba_goodshoot.wav
sound/echoes/barney/ba_gundying.wav
sound/echoes/barney/ba_gungiver.wav
sound/echoes/barney/ba_hello1.wav
sound/echoes/barney/ba_laugh01.wav
sound/echoes/barney/ba_laugh02.wav
sound/echoes/barney/ba_laugh03.wav
sound/echoes/barney/ba_longnite.wav
sound/echoes/barney/ba_milkill.wav
sound/echoes/barney/ba_movie.wav
sound/echoes/barney/ba_power2.wav
sound/echoes/barney/ba_power4.wav
sound/echoes/barney/ba_protect.wav
sound/echoes/barney/ba_safe1.wav
sound/echoes/barney/ba_security2_admin.wav
sound/echoes/barney/ba_shit.wav
sound/echoes/barney/ba_soldier.wav
sound/echoes/barney/ba_spawn.wav
sound/echoes/barney/c1a4_ba_octo2.wav
sound/echoes/barney/goodteam.wav
sound/echoes/barney/map10_battle.wav
sound/echoes/barney/mil_nevermakeit.wav
sound/echoes/barney/nocandoo.wav
sound/echoes/barney/suredo.wav
sound/echoes/barney/withoutme.wav
sound/echoes/car/caralarm.wav
sound/echoes/car/cararrive.wav
sound/echoes/car/cardoor.wav
sound/echoes/car/carlock.wav
sound/echoes/car/caropen.wav
sound/echoes/car/caropenalarm.wav
sound/echoes/car/carshutoff.wav
sound/echoes/common/bodydrop3.wav
sound/echoes/common/bodydrop4.wav
sound/echoes/common/bodysplat.wav
sound/echoes/common/npc_step1.wav
sound/echoes/common/npc_step2.wav
sound/echoes/common/npc_step3.wav
sound/echoes/common/npc_step4.wav
sound/echoes/common/wpn_denyselect.wav
sound/echoes/common/wpn_hudoff.wav
sound/echoes/common/wpn_hudon.wav
sound/echoes/common/wpn_moveselect.wav
sound/echoes/common/wpn_select.wav
sound/echoes/debris/bustflesh1.wav
sound/echoes/debris/bustflesh2.wav
sound/echoes/debris/flesh1.wav
sound/echoes/debris/flesh2.wav
sound/echoes/debris/flesh3.wav
sound/echoes/debris/flesh5.wav
sound/echoes/debris/flesh6.wav
sound/echoes/debris/flesh7.wav
sound/echoes/debris/pushbox1.wav
sound/echoes/debris/pushbox2.wav
sound/echoes/debris/pushbox3.wav
sound/echoes/dweller/stalker_scream1.wav
sound/echoes/dweller/stalker_scream2.wav
sound/echoes/dweller/stalker_scream4.wav
sound/echoes/echoes_materials.txt
sound/echoes/env/amb_concrete1.wav
sound/echoes/env/amb_concrete2.wav
sound/echoes/env/amb_mechanical.wav
sound/echoes/env/amb_radio_01.wav
sound/echoes/env/amb_wind.wav
sound/echoes/env/amb_zombies.wav
sound/echoes/env/battle_loop1.wav
sound/echoes/env/battle_loop2.wav
sound/echoes/env/cart_shutdown.wav
sound/echoes/env/colette_stop2.wav
sound/echoes/env/door_smack.wav
sound/echoes/env/excuseme.wav
sound/echoes/env/facility_outdoor.wav
sound/echoes/env/fire.wav
sound/echoes/env/firebell.wav
sound/echoes/env/generator_alarm.wav
sound/echoes/env/gina_mad1.wav
sound/echoes/env/handdryer.wav
sound/echoes/env/jet_flyby_quick.wav
sound/echoes/env/lightoff.wav
sound/echoes/env/portalblast.wav
sound/echoes/env/rumble.wav
sound/echoes/env/scanner.wav
sound/echoes/env/screamscare.wav
sound/echoes/env/steamscare.wav
sound/echoes/env/te_strike1.wav
sound/echoes/env/te_strike2.wav
sound/echoes/env/terrain_rumble1.wav
sound/echoes/env/toilet.wav
sound/echoes/env/trainhorn.wav
sound/echoes/env/tram1.wav
sound/echoes/env/tram2.wav
sound/echoes/env/tunnel.wav
sound/echoes/env/tunnel2.wav
sound/echoes/env/vent.wav
sound/echoes/env/water_crash1.wav
sound/echoes/env/water_crash2.wav
sound/echoes/env/water_flowing1.wav
sound/echoes/env/water_flowing2.wav
sound/echoes/env/water_flowing3.wav
sound/echoes/env/waterrun.wav
sound/echoes/env/xen_heart.wav
sound/echoes/flyer/alienflyby1.wav
sound/echoes/flyer/alienflyby2.wav
sound/echoes/flyer/flyer_appear.wav
sound/echoes/flyer/flyer_die.wav
sound/echoes/flyer/flyer_idle.wav
sound/echoes/flyer/flyerbeam.wav
sound/echoes/flyer/ospreycrash.wav
sound/echoes/flyer/zapper_warmup2.wav
sound/echoes/gman/Fadein.wav
sound/echoes/gman/gman_again.wav
sound/echoes/gman/gman_belong.wav
sound/echoes/gman/gman_comebacknow.wav
sound/echoes/gman/gman_cutoff.wav
sound/echoes/gman/gman_dream.wav
sound/echoes/gman/gman_getbackhere.wav
sound/echoes/gman/gman_huff.wav
sound/echoes/gman/gman_inhale.wav
sound/echoes/gman/gman_intro.wav
sound/echoes/gman/gman_laugh01.wav
sound/echoes/gman/gman_meetagain.wav
sound/echoes/gman/gman_nicetohaveyou.wav
sound/echoes/gman/gman_notforlong.wav
sound/echoes/gman/gman_notthistime.wav
sound/echoes/gman/gman_ohno.wav
sound/echoes/gman/gman_oldtimes.wav
sound/echoes/gman/gman_payattention.wav
sound/echoes/gman/gman_prepare.wav
sound/echoes/gman/gman_ratherbusy.wav
sound/echoes/gman/gman_scare.wav
sound/echoes/gman/gman_see.wav
sound/echoes/gman/gman_snarl01.wav
sound/echoes/gman/gman_snarl02.wav
sound/echoes/gman/gman_snarl03.wav
sound/echoes/gman/gman_thatsallfornow.wav
sound/echoes/gman/gman_thatwillbeall.wav
sound/echoes/gman/gman_wellsh.wav
sound/echoes/gman/gman_wellsh2.wav
sound/echoes/gman/gman_wemeet.wav
sound/echoes/gman/seerremove.wav
sound/echoes/gman/Whoosh0.wav
sound/echoes/gman/Whoosh1.wav
sound/echoes/gman/Whoosh2.wav
sound/echoes/hgrunt/gr_mgun1.wav
sound/echoes/hgrunt/gr_mgun2.wav
sound/echoes/hgrunt/gr_reload1.wav
sound/echoes/hgrunt/gr_snark.wav
sound/echoes/hgrunt/sniper_fire.wav
sound/echoes/intro/intro_eli_1.wav
sound/echoes/intro/intro_eli_2.wav
sound/echoes/intro/intro_eli_3.wav
sound/echoes/intro/intro_eli_4.wav
sound/echoes/intro/intro_eli_5.wav
sound/echoes/intro/intro_eli_6.wav
sound/echoes/intro/intro_eli_7.wav
sound/echoes/intro/intro_siren1.wav
sound/echoes/items/9mmclip1.wav
sound/echoes/items/9mmclip2.wav
sound/echoes/items/bafake_die.wav
sound/echoes/items/bafake_freeze.wav
sound/echoes/items/clipinsert1.wav
sound/echoes/items/cliprelease1.wav
sound/echoes/items/flashlight1.wav
sound/echoes/items/gunpickup2.wav
sound/echoes/items/hevdead.wav
sound/echoes/items/weapondrop1.wav
sound/echoes/media/Half-Life02.mp3
sound/echoes/media/Half-Life03.mp3
sound/echoes/media/Half-Life04.mp3
sound/echoes/media/Half-Life05.mp3
sound/echoes/media/Half-Life07.mp3
sound/echoes/media/Half-Life08.mp3
sound/echoes/media/Half-Life10.mp3
sound/echoes/media/Half-Life12.mp3
sound/echoes/media/Half-Life13.mp3
sound/echoes/media/Half-Life14.mp3
sound/echoes/media/Half-Life15.mp3
sound/echoes/media/Prospero01.mp3
sound/echoes/media/Prospero02.mp3
sound/echoes/media/Prospero03.mp3
sound/echoes/media/Prospero05.mp3
sound/echoes/media/Suspense02.mp3
sound/echoes/media/Suspense07.mp3
sound/echoes/military/exitdoorpanel.wav
sound/echoes/military/lights_off.wav
sound/echoes/military/major_mortar.wav
sound/echoes/military/mil_alienambush.wav
sound/echoes/military/mil_backuphere.wav
sound/echoes/military/mil_backupnorth.wav
sound/echoes/military/mil_bastards.wav
sound/echoes/military/mil_casualties.wav
sound/echoes/military/mil_displacer.wav
sound/echoes/military/mil_eliminate.wav
sound/echoes/military/mil_freemandown.wav
sound/echoes/military/mil_gargcoming.wav
sound/echoes/military/mil_gotyou.wav
sound/echoes/military/mil_heavy.wav
sound/echoes/military/mil_hold.wav
sound/echoes/military/mil_laugh.wav
sound/echoes/military/mil_letsfight.wav
sound/echoes/military/mil_mother.wav
sound/echoes/military/mil_notfreeman.wav
sound/echoes/military/mil_onturret.wav
sound/echoes/military/mil_retreat.wav
sound/echoes/military/mil_rocket1.wav
sound/echoes/military/mil_scidie.wav
sound/echoes/military/mil_suppress.wav
sound/echoes/military/mil_sweep.wav
sound/echoes/military/mil_tank1.wav
sound/echoes/military/mil_tank2.wav
sound/echoes/military/mil_tank3.wav
sound/echoes/military/mil_tankflee.wav
sound/echoes/military/mil_tankflee2.wav
sound/echoes/military/mil_targetmortar.wav
sound/echoes/military/mil_toohot.wav
sound/echoes/military/mortar_activate.wav
sound/echoes/military/ofmortar.wav
sound/echoes/military/osprey_shit.wav
sound/echoes/military/static.wav
sound/echoes/military/tankdrivein1.wav
sound/echoes/military/tankdrivein2.wav
sound/echoes/military/tripwire.wav
sound/echoes/military/truck_stop.wav
sound/echoes/military/turretrot1.wav
sound/echoes/military/turretrot2.wav
sound/echoes/outtro/airraidsiren.wav
sound/echoes/outtro/alyx-gordon.wav
sound/echoes/outtro/baby1.wav
sound/echoes/outtro/citadel_drone_loop3.wav
sound/echoes/outtro/eli_basehouse.wav
sound/echoes/outtro/eli_ohalyx.wav
sound/echoes/outtro/eli_rememberwife.wav
sound/echoes/outtro/eli_rescuedher.wav
sound/echoes/outtro/eli_whathappened.wav
sound/echoes/outtro/explosion01.wav
sound/echoes/outtro/explosion02.wav
sound/echoes/outtro/nuke_final.wav
sound/echoes/outtro/portal1.wav
sound/echoes/outtro/portal2.wav
sound/echoes/outtro/portal3.wav
sound/echoes/outtro/portal4.wav
sound/echoes/outtro/seer_scream.wav
sound/echoes/outtro/teleport_weird_voices1.wav
sound/echoes/outtro/teleport_weird_voices2.wav
sound/echoes/player/pl_duct1.wav
sound/echoes/player/pl_duct2.wav
sound/echoes/player/pl_duct3.wav
sound/echoes/player/pl_duct4.wav
sound/echoes/player/pl_fallpain3.wav
sound/echoes/scientist/_comma.wav
sound/echoes/scientist/breakthings.wav
sound/echoes/scientist/d01_sci10_interesting.wav
sound/echoes/scientist/d01_sci14_right.wav
sound/echoes/scientist/d06_sci01_lambdalabs.wav
sound/echoes/scientist/darkkill.wav
sound/echoes/scientist/drunk.wav
sound/echoes/scientist/dweller_help.wav
sound/echoes/scientist/dweller_notagain.wav
sound/echoes/scientist/faller_stayback.wav
sound/echoes/scientist/fallinsane.wav
sound/echoes/scientist/fork_impossible.wav
sound/echoes/scientist/fork_phd.wav
sound/echoes/scientist/fork_theoretically.wav
sound/echoes/scientist/funny_toilet1.wav
sound/echoes/scientist/funny_toilet2.wav
sound/echoes/scientist/funny_toilet3.wav
sound/echoes/scientist/guardknows.wav
sound/echoes/scientist/nil.wav
sound/echoes/scientist/nogrant.wav
sound/echoes/scientist/okgetout.wav
sound/echoes/scientist/sc_coming.wav
sound/echoes/scientist/sc_holdyourself.wav
sound/echoes/scientist/sc_leavemealone.wav
sound/echoes/scientist/sc_outofhere.wav
sound/echoes/scientist/sc_please.wav
sound/echoes/scientist/sc_power2.wav
sound/echoes/scientist/sc_yard_box3.wav
sound/echoes/scientist/sc_yard_box4.wav
sound/echoes/scientist/sci_fear8.wav
sound/echoes/scientist/snarkbody.wav
sound/echoes/scientist/sneeze.wav
sound/echoes/scientist/thankgod.wav
sound/echoes/scientist/tramangry.wav
sound/echoes/scientist/tramcough.wav
sound/echoes/voxlines/MAP12_VOX1.wav
sound/echoes/voxlines/MAP12_VOX2.wav
sound/echoes/voxlines/MAP12_VOX3.wav
sound/echoes/voxlines/MAP12_VOX4.wav
sound/echoes/voxlines/MAP12_VOX6.wav
sound/echoes/voxlines/MAP14_ALERT1.wav
sound/echoes/voxlines/MAP15_VOXLIFT.wav
sound/echoes/voxlines/MAP3_INDOOR0.wav
sound/echoes/voxlines/MAP4_VOX1.wav
sound/echoes/voxlines/MAP4_VOX2.wav
sound/echoes/voxlines/MAP4_VOX3.wav
sound/echoes/voxlines/MAP9_BRIDGE1.wav
sound/echoes/voxlines/MAP9_BRIDGE2.wav
sound/echoes/voxlines/MAP9_BRIDGE4.wav
sound/echoes/voxlines/MILCOM.wav
sound/echoes/voxlines/VOX_SHUTDOWN.wav
sound/echoes/weapons/357_cock1.wav
sound/echoes/weapons/357_shot1.wav
sound/echoes/weapons/357_shot2.wav
sound/echoes/weapons/bullet_hit1.wav
sound/echoes/weapons/bullet_hit2.wav
sound/echoes/weapons/cbar_hit1.wav
sound/echoes/weapons/cbar_hit2.wav
sound/echoes/weapons/cbar_hitbod1.wav
sound/echoes/weapons/cbar_hitbod2.wav
sound/echoes/weapons/cbar_hitbod3.wav
sound/echoes/weapons/cbar_miss1.wav
sound/echoes/weapons/dbarrel1.wav
sound/echoes/weapons/dryfire1.wav
sound/echoes/weapons/explode3.wav
sound/echoes/weapons/explode4.wav
sound/echoes/weapons/explode5.wav
sound/echoes/weapons/g_bounce1.wav
sound/echoes/weapons/g_bounce2.wav
sound/echoes/weapons/g_bounce3.wav
sound/echoes/weapons/grenade_hit1.wav
sound/echoes/weapons/grenade_hit2.wav
sound/echoes/weapons/grenade_hit3.wav
sound/echoes/weapons/hks1.wav
sound/echoes/weapons/hks2.wav
sound/echoes/weapons/hks3.wav
sound/echoes/weapons/mine_activate.wav
sound/echoes/weapons/mine_charge.wav
sound/echoes/weapons/mine_deploy.wav
sound/echoes/weapons/mortar.wav
sound/echoes/weapons/pl_gun1.wav
sound/echoes/weapons/pl_gun2.wav
sound/echoes/weapons/pl_gun3.wav
sound/echoes/weapons/ric1.wav
sound/echoes/weapons/ric2.wav
sound/echoes/weapons/ric3.wav
sound/echoes/weapons/ric4.wav
sound/echoes/weapons/ric5.wav
sound/echoes/weapons/rocket1.wav
sound/echoes/weapons/rocketfire1.wav
sound/echoes/weapons/sbarrel1.wav
sound/echoes/weapons/scock1.wav
sound/echoes/weapons/sshell1.wav
sound/echoes/weapons/sshell2.wav
sound/echoes/weapons/sshell3.wav
sound/echoes/weapons/xbow_fire1.wav
sound/echoes/weapons/xbow_fly1.wav
sound/echoes/weapons/xbow_hit1.wav
sound/echoes/weapons/xbow_hit2.wav
sound/echoes/weapons/xbow_hitbod1.wav
sound/echoes/weapons/xbow_hitbod2.wav
sound/echoes/weapons/xbow_reload1.wav
