// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

gfx/env/grassbk.tga
gfx/env/grassdn.tga
gfx/env/grassft.tga
gfx/env/grasslf.tga
gfx/env/grassrt.tga
gfx/env/grassup.tga
gfx/env/skylinebk.tga
gfx/env/skylinedn.tga
gfx/env/skylineft.tga
gfx/env/skylinelf.tga
gfx/env/skylinert.tga
gfx/env/skylineup.tga
gfx/env/snowcliffbk.tga
gfx/env/snowcliffdn.tga
gfx/env/snowcliffft.tga
gfx/env/snowclifflf.tga
gfx/env/snowcliffrt.tga
gfx/env/snowcliffup.tga
models/mario_keys/cannon_guy.mdl
sound/mario_keys/billblow.wav
sound/mario_keys/bowlaugh.wav
sound/mario_keys/bowser.wav
sound/mario_keys/coin.wav
sound/mario_keys/falling1.wav
sound/mario_keys/falls.wav
sound/mario_keys/fire_1.wav
sound/mario_keys/koopa.ogg
sound/mario_keys/koopawin.wav
sound/mario_keys/lavaland.ogg
sound/mario_keys/loopsteps.wav
sound/mario_keys/merry.wav
sound/mario_keys/outdoor.wav
sound/mario_keys/pipewarp.wav
sound/mario_keys/snow.ogg
sound/mario_keys/thanks.wav
sound/mario_keys/toons.wav
sound/mario_keys/win.ogg
sprites/cloud.spr
