dmc.wad
halflife.wad
liquids.wad
mommamesa.wad
op4ctf.wad
Opfor.wad
tfc.WAD
xeno.wad

maps/mommamesa.cfg
maps/mommamesa_motd.txt
maps/mommamesa_skl.cfg
maps/mommamesa.gmr
maps/mommamesa.res

models/mommamesa/bman_2.mdl
models/mommamesa/bman_2T.mdl
models/mommamesa/giantroach.mdl
models/mommamesa/hevgrunt.mdl
models/mommamesa/mantaray.mdl
models/mommamesa/prisoner.mdl
models/mommamesa/prisoner01.mdl
models/mommamesa/v_shotgun.mdl
models/mommamesa/w_blue_suit.mdl
models/mommamesa/w_blue_suitt.mdl
models/mommamesa/scizombie.mdl
models/mommamesa/wheelchair.mdl

sprites/mommamesa/escape_win_list.spr
sprites/mommamesa/mm_pinkslip.spr
sprites/mommamesa/mm_pinkslip2.spr
sprites/mommamesa/pizzaparty.spr
sprites/mommamesa/prison_fail_list.spr

sound/mommamesa/ba_gunshot.txt
sound/mommamesa/g3.txt
sound/mommamesa/generator.txt
sound/mommamesa/prisoner.txt
sound/mommamesa/ba_attack2.wav
sound/mommamesa/effect_on.wav
sound/mommamesa/explode.wav
sound/mommamesa/lava.wav
sound/mommamesa/lose.ogg
sound/mommamesa/null.wav
sound/mommamesa/selfdestruct.ogg
sound/mommamesa/trap_door.wav
sound/mommamesa/trap_mines.wav
sound/mommamesa/trap_turrets.wav
sound/mommamesa/uplink_begin.wav
sound/mommamesa/waveloop.wav
sound/mommamesa/win.ogg
sound/mommamesa/xtal_down1.wav
sound/mommamesa/pinkslip.ogg
sound/mommamesa/weirdlaugh1.wav
sound/mommamesa/weirdlaugh2.wav
sound/mommamesa/gunshot/aug-1.wav
sound/mommamesa/gunshot/p90-1.wav
sound/mommamesa/music/___music_credits.txt
sound/mommamesa/music/caves.ogg
sound/mommamesa/music/chords.mp3
sound/mommamesa/music/citadel.ogg
sound/mommamesa/music/escape.ogg
sound/mommamesa/music/fishproblem.ogg
sound/mommamesa/music/hitmen.ogg
sound/mommamesa/music/outro_01.ogg
sound/mommamesa/music/outro_02.ogg
sound/mommamesa/music/outro_03.ogg
sound/mommamesa/music/perimeter.ogg
sound/mommamesa/music/perimeter_idle.ogg
sound/mommamesa/music/perimeter_intro.ogg
sound/mommamesa/music/portal_lab.ogg
sound/mommamesa/music/theroach.ogg
sound/mommamesa/music/training.wav
sound/mommamesa/music/tunnels.ogg
sound/mommamesa/music/uplink.ogg
sound/mommamesa/music/victory.ogg
