// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

Infected.wad
models/gus/v_357.mdl
models/gus/v_9mmar.mdl
models/gus/v_9mmhandgun.mdl
models/gus/v_chub.mdl
models/gus/v_crossbow.mdl
models/gus/v_crowbar.mdl
models/gus/v_desert_eagle.mdl
models/gus/v_displacer.mdl
models/gus/v_egon.mdl
models/gus/v_gauss.mdl
models/gus/v_grenade.mdl
models/gus/v_m16a2.mdl
models/gus/v_m40a1.mdl
models/gus/v_medkit.mdl
models/gus/v_pipe_wrench.mdl
models/gus/v_rpg.mdl
models/gus/v_satchel.mdl
models/gus/v_satchel_radio.mdl
models/gus/v_saw.mdl
models/gus/v_shotgun.mdl
models/gus/v_spore_launcher.mdl
models/gus/v_squeak.mdl
models/gus/v_tripmine.mdl
models/gus/v_uzi.mdl
models/gus/w_helmet_gus.mdl
models/infected/GLOBE_AnomMat.mdl
models/infected/gun_mag.mdl
models/infected/wrangler.mdl
sound/Donald/deny.wav
sound/Donald/line1.wav
sound/Donald/line2.wav
sound/Donald/line3.wav
sound/Donald/line4.wav
sound/Donald/line5.wav
sound/infected/infected_materials.txt
sound/infected/n0a1_warning_line.wav
sound/otis/goodone.wav
sound/otis/long_day.wav
sound/owen/Bathrooms.wav
sound/owen/Cleanpants.wav
sound/owen/Colamachines.wav
sound/owen/EnergyDisplacer.wav
sound/owen/Fine.wav
sound/owen/Funshooting.wav
sound/owen/GetSuit.wav
sound/owen/Godcansee.wav
sound/owen/GODDAMNIT.wav
sound/owen/Imhere.wav
sound/owen/Impushing.wav
sound/owen/Impushingchunks.wav
sound/owen/Ishouldbenaked.wav
sound/owen/Itsamazing.wav
sound/owen/Ivecared.wav
sound/owen/Light.wav
sound/owen/Lunch.wav
sound/owen/MisterBackman.wav
sound/owen/Politicalyincorrect.wav
sound/owen/ResetComm.wav
sound/owen/Ronald.wav
sound/owen/screaming.wav
sound/owen/seethis.wav
sound/owen/ServerComm.wav
sound/owen/Shit.wav
sound/owen/Stopthat.wav
sound/owen/Stupid1.wav
sound/owen/Stupid2.wav
sound/owen/Takedamage2.wav
sound/owen/Tappportal.wav
sound/owen/Thatsthekernel.wav
sound/owen/Thatsthewayitis.wav
sound/owen/Waitforroy.wav
sound/owen/Whatsmell.wav
sound/owen/Whois.wav
sound/owen/WifeHypnotist.wav
sound/owen/Wipe.wav
sound/owen/Youreinsane.wav
sound/owen/Youshouldbenaked.wav
sound/Roy/Biome1.wav
sound/Roy/Biome2.wav
sound/Roy/Biome3.wav
sound/Roy/Biome4.wav
sound/Roy/BiomeEsc1.wav
sound/Roy/BiomeEsc2.wav
sound/Roy/Denied1.wav
sound/Roy/Denied2.wav
sound/Roy/Fear1.wav
sound/Roy/Fear2.wav
sound/Roy/Fear3.wav
sound/Roy/Follow1.wav
sound/Roy/Follow2.wav
sound/Roy/Follow3.wav
sound/Roy/Follow4.wav
sound/Roy/Heal1.wav
sound/Roy/Heal2.wav
sound/Roy/Idle1.wav
sound/Roy/Idle2.wav
sound/Roy/Idle3.wav
sound/Roy/Idle4.wav
sound/Roy/Idle5.wav
sound/Roy/Intro1.wav
sound/Roy/Intro2.wav
sound/Roy/Intro3.wav
sound/Roy/Intro4.wav
sound/Roy/Outro1.wav
sound/Roy/Outro2.wav
sound/Roy/Serverroom1.wav
sound/Roy/Serverroom2.wav
sound/Roy/Serverroom3.wav
sound/Roy/Serverroom4.wav
sound/Roy/Serverroom5.wav
sound/Roy/Stop1.wav
sound/Roy/Stop2.wav
sound/Roy/Stop3.wav
sound/Roy/Stop4.wav
sound/tram/ba_tram04.wav
