barney.wad
decals.wad
gfx/env/dfcliffbk.bmp
gfx/env/dfcliffbk.tga
gfx/env/dfcliffdn.bmp
gfx/env/dfcliffdn.tga
gfx/env/dfcliffft.bmp
gfx/env/dfcliffft.tga
gfx/env/dfclifflf.bmp
gfx/env/dfclifflf.tga
gfx/env/dfcliffrt.bmp
gfx/env/dfcliffrt.tga
gfx/env/dfcliffup.bmp
gfx/env/dfcliffup.tga
halflife.wad
liquids.wad
maps/polar_rescue.cfg
maps/polar_rescue.txt
maps/polar_rescue_motd.txt
maps/polar_rescue_skl.cfg
models/adamr/backpack_sven.mdl
models/adamr/ceiling_lamp.mdl
models/adamr/key.mdl
models/adamr/keycard_l1.mdl
models/adamr/keycard_l1T.mdl
models/adamr/keycard_l2.mdl
models/adamr/keycard_l2T.mdl
models/adamr/keycard_l3.mdl
models/adamr/keycard_l3T.mdl
models/adamr/keyT.mdl
models/adamr/weapons/gold357/p_gold357.mdl
models/adamr/weapons/gold357/v_gold357.mdl
models/adamr/weapons/gold357/v_gold357_op4.mdl
models/adamr/weapons/gold357/w_gold357.mdl
models/blkop_apache.mdl
models/ginsmodels/gins_clock.mdl
models/ginsmodels/gins_substation.mdl
models/ginsmodels/gins_trashcan.mdl
models/ginsmodels/lag_radio.mdl
models/greysnake/hgrunt_opfor.mdl
models/greysnake/massn.mdl
models/osprey.mdl
models/player/helmet/helmet.mdl
models/revil/furnature/sink.mdl
models/revil/furnature/toilet.mdl
opfor.wad
sound/adamr/bigexplode.wav
sound/adamr/blipblipblip.wav
sound/adamr/electricbuzz.wav
sound/adamr/hgrunt/call_backup.wav
sound/adamr/music/alec-eiffel.wav
sound/adamr/polar_rescue/10_minutes_remaining.wav
sound/adamr/polar_rescue/15_minutes_remaining.wav
sound/adamr/polar_rescue/3_minutes_remaining.wav
sound/adamr/polar_rescue/5_minutes_remaining.wav
sound/adamr/polar_rescue/60_seconds_remaining.wav
sound/adamr/polar_rescue/missileroom_door_first_speech.wav
sound/adamr/polar_rescue/vault_door_first_speech.wav
sound/omg/nomble.wav
sound/tur/labyrinth.wav
sprites/adamr/arrow_destroy.spr
sprites/adamr/arrow_take.spr
sprites/adamr/arrow_use.spr
xeno.wad
