// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/player/cl_scientist1/cl_scientist1.mdl
models/player/cl_scientist2/cl_scientist2.mdl
models/player/cl_scientist3/cl_scientist3.mdl
models/player/cl_scientist4/cl_scientist4.mdl
models/player/cl_scientist5/cl_scientist5.mdl
models/player/cl_scientist6/cl_scientist6.mdl
models/residuallife/aworker.mdl
models/residuallife/aworker01.mdl
models/residuallife/aworker02.mdl
models/residuallife/cleansuit_scientist.mdl
models/residuallife/scientist.mdl
models/residuallife/scientist01.mdl
models/residuallife/scientist02.mdl
models/residuallife/scientist03.mdl
models/residuallife/scientist04.mdl
models/residuallife/scientist05.mdl
models/residuallife/scientist06.mdl
models/residuallife/scientist07.mdl
models/residuallife/scientist08.mdl
models/residuallife/scientist09.mdl
models/residuallife/scientist10.mdl
models/residuallife/weapons/v_357.mdl
models/residuallife/weapons/v_9mmar.mdl
models/residuallife/weapons/v_9mmhandgun.mdl
models/residuallife/weapons/v_crossbow.mdl
models/residuallife/weapons/v_crowbar.mdl
models/residuallife/weapons/v_desert_eagle2.mdl
models/residuallife/weapons/v_egon.mdl
models/residuallife/weapons/v_gauss.mdl
models/residuallife/weapons/v_grenade.mdl
models/residuallife/weapons/v_hgun.mdl
models/residuallife/weapons/v_m16a2.mdl
models/residuallife/weapons/v_medkit.mdl
models/residuallife/weapons/v_rpg.mdl
models/residuallife/weapons/v_satchel.mdl
models/residuallife/weapons/v_satchel_radio.mdl
models/residuallife/weapons/v_shotgun.mdl
models/residuallife/weapons/v_squeak2.mdl
models/residuallife/weapons/v_tripmine.mdl
models/residuallife/xenocrab.mdl
rl_.wad
sound/residuallife/barney/ba_late.wav
sound/residuallife/barney/ba_security2_desk0.wav
sound/residuallife/barney/s02ba_hello.wav
sound/residuallife/barney/s02ba_pl_door.wav
sound/residuallife/barney/sk02_ba_headdown.wav
sound/residuallife/debris/a_teleport.wav
sound/residuallife/fgrunt/ok03b_fg01.wav
sound/residuallife/fvox/inject1.wav
sound/residuallife/gman/gman_intro_talk0.wav
sound/residuallife/gman/intro_gman_tulk1a.wav
sound/residuallife/gman/intro_gman_tulk1b.wav
sound/residuallife/ngrunt/ng_idle0.wav
sound/residuallife/ngrunt/ng_idle1.wav
sound/residuallife/ngrunt/ng_idle2.wav
sound/residuallife/ngrunt/ng_idle3.wav
sound/residuallife/residual_materials.txt
sound/residuallife/scientist/dk01_sci_talk.wav
sound/residuallife/scientist/sc_crazer.wav
