sc_contrahdl.wad
maps/sc_contratosc_c1_beta.bsp
maps/sc_contratosc_c1_beta.cfg
maps/sc_contratosc_c1_beta.res
maps/sc_contratosc_c1_beta_skl.cfg
maps/sc_contrahdl.gmr
maps/sc_contrahdl.gsr
models/sc_contrahdl/contra_barnabus.mdl
models/sc_contrahdl/contra_massn.mdl
sound/sc_contrahdl/hdl_alert.wav
sound/sc_contrahdl/hdl_explode1.wav
sound/sc_contrahdl/hdl_shot.wav
sound/sc_contrahdl/hdl_shot_2.wav
sound/sc_contrahdl/hdl03.wav
sound/sc_contrahdl/bgms/3.ogg
sound/sc_contrahdl/bgms/3_loop.ogg
sprites/contra/contra_bullet1.spr
sprites/contra/contra_bullet2.spr
sprites/contra/r.spr
sprites/contra/m.spr
sprites/contra/s.spr
sprites/contra/l.spr
sprites/contra/f.spr