nw.wad
nw_xeno.wad
submerged.wad
neilm2.wad
neilm4.wad
models/sc_robination/dead_tree02.mdl
models/sc_robination/dead_tree08.mdl
models/sc_robination/gasmask_item.mdl
models/sc_robination/keycard_centered.mdl
models/sc_robination/radio_part.mdl
scripts/maps/sc_robination/cross_map_item_inv.as
scripts/maps/sc_robination/customkv.as
scripts/maps/sc_robination/drown.as
scripts/maps/sc_robination/mark_ammo.as
scripts/maps/sc_robination/settime.as
sound/sc_robination/alarm001.wav
sound/sc_robination/arc_welder_long.wav
sound/sc_robination/cuboos_alien_horn2.wav
sound/sc_robination/item_respawn.wav
sound/sc_robination/petardo1.wav
sound/sc_robination/crash.wav
sound/sc_robination_revised/sc_robination_revised.gsr
maps/sc_robination_revised.txt
maps/sc_robination_revised_motd.txt
maps/sc_robination_revised.cfg
maps/sc_robination_revised_skl.cfg
