// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/shl/hev_sci.mdl
models/shl/hevsci.mdl
models/shl/race.mdl
shl.wad
sound/shl/dbarrel1.wav
sound/shl/hevbarney/hks1.wav
sound/shl/hevbarney/hks2.wav
sound/shl/hevbarney/hks3.wav
sound/shl/hevbarney/sbarrel1.wav
sound/shl/hevbarney/scock1.wav
sound/shl/hevsci/run1.wav
sound/shl/m41a_3round.wav
sound/shl/m41a_single.wav
sound/shl/m41aglauncher.wav
sound/shl/m41aglauncher2.wav
sound/shl/mecanical.wav
sound/shl/piano.wav
sound/shl/race/race_alert1.wav
sound/shl/race/race_alert2.wav
sound/shl/race/race_die1.wav
sound/shl/race/race_die2.wav
sound/shl/race/race_idle1.wav
sound/shl/race/race_idle2.wav
sound/shl/race/race_idle3.wav
sound/shl/race/race_idle4.wav
sound/shl/race/race_pain1.wav
sound/shl/race/race_pain2.wav
sound/shl/race/race_pain3.wav
sound/shl/race/race_pain4.wav
sound/shl/race/race_pain5.wav
sound/shl/scientist/shl2_sci_go.wav
sound/shl/scientist/shl2_sci_goingon.wav
sound/shl/scientist/shl2_sci_here.wav
sound/shl/scientist/shl6_sci_outofhere.wav
sound/shl/scientist/shl9_sci_destroy.wav
sound/shl/scientist/shl9_sci_reactor.wav
sound/shl/scientist/shl_ship_conquerearth.wav
sound/shl/scientist/shl_ship_destroyship.wav
sound/shl/scientist/shl_ship_findyourway.wav
sound/shl/scientist/shl_ship_mothership.wav
sound/shl/scientist/shl_ship_otherhumans.wav
sound/shl/scientist/shl_ship_rescuethem.wav
sound/shl/scientist/shl_ship_stopthem.wav
sound/shl/scientist/shlwork_sample.wav
sound/shl/set.wav
sound/shl/spf_reload1.wav
sound/shl/weapons/plasma1.wav
sound/shl/weapons/plasma2.wav
